Updated Azure CPI config docs to include new and existing features…
cloudfoundry/docs-bosh pull request #761
Opened 2021-12-10 21:03 UTC by Justin-W

… related to the following Azure CPI PRs/issues:

- https://github.com/cloudfoundry/bosh-azure-cpi-release/pull/651 (Fixes https://github.com/cloudfoundry/bosh-azure-cpi-release/issues/644)
- https://github.com/cloudfoundry/bosh-azure-cpi-release/pull/541 (Fixed https://github.com/cloudfoundry/bosh-azure-cpi-release/issues/328)
- https://github.com/cloudfoundry/bosh-azure-cpi-release/pull/638 (Fixed https://github.com/cloudfoundry/bosh-azure-cpi-release/issues/111)

Note: This commit assumes that PR cloudfoundry/bosh-azure-cpi-release/pull/651 will be included in a new `v37.7.0` release of the Azure CPI (in order to properly document the CPI version requirements of new features). If PR # 651 is instead included in a different CPI version, then this PR will need to be amended appropriately.

2021-12-14 14:13 UTC, ramonskie approved these changes

2021-12-15 09:49 UTC, beyhan requested changes
I hink it make sense to extend the `Example of a load balancer` now because there are more configuration options.

2021-12-15 18:41 UTC, Justin-W commented
> I hink it make sense to extend the `Example of a load balancer` now because there are more configuration options.

Done. And also added 3 examples for `application_gateway`.

2021-12-20 13:04 UTC, beyhan approved these changes

2022-01-13 15:39 UTC, ramonskie commented
blocked as its depending on https://github.com/cloudfoundry/bosh-azure-cpi-release/pull/651

2022-02-02 14:19 UTC, merged