Correct typos
cloudfoundry/docs-bosh pull request #781
Opened 2022-12-06 21:34 UTC by mrosecrance

The AZ doc had a few odd grammar phrasings or extra veriage. Removed to hopefully help readability

2022-12-16 21:58 UTC, bgandon requested changes
That’s already nice and good catches, but we can do a bit better, and avoid having to come back to it later.

2022-12-16 21:58 UTC, bgandon commented on content/azs.md
> +>   With some CPIs AZS are referenced in the Subnet configuration of the cloud-config networks block. This means that moving AZs can have networking implications. E.g. networks can be Zonal ( e.g. AW
We can do a bit better, removing extra spaces next to parenthesis.

Plus, the “_referenced in the Subnet configuration of the cloud-config networks block_” can still be improved.

Something like “_With some CPIs, availability zones are tied to subnets, as specified by the networks section of the Cloud Config_”

2022-12-16 21:58 UTC, bgandon commented on content/azs.md
> +> - bosh does not migrate persistent disk contents across AZs. Persistent disks attached to a vm that is moved to another AZ will be orphaned and eventually deleted by bosh.
At least capitalize “Bosh”

2022-12-23 09:29 UTC, ramonskie approved these changes

2023-01-12 15:36 UTC, rkoster commented
@mrosecrance can you take a loot at the changes requested by @bgandon

2023-01-19 15:32 UTC, rkoster commented
ping @mrosecrance

2023-02-02 15:50 UTC, rkoster commented
@bgandon, we are gonna go ahead an merged this PR, because it already improves upon the current state of the docs. If you would like the further improve it even more please create a separate PR.

2023-02-02 15:50 UTC, merged