Add missing docs about Azure Managed Identity usage in VM extension
cloudfoundry/docs-bosh pull request #814
Opened 2023-11-13 13:10 UTC by metskem

There was some missing documentation about how to use managed identities with a VM extension.

2023-11-20 17:21 UTC, ystros requested changes
Good catch on these missing docs!  I think it just needs a slight update to the example.

2023-11-20 17:21 UTC, ystros commented on content/azure-cpi.md
> +    user_assigned_identity_name: <name of managed identity>
I believe this example should be nested under the `managed_identity` key, e.g.
```yaml
  cloud_properties:
    managed_identity:
        type: UserAssigned
        user_assigned_identity_name: <name of managed identity>
```

2023-11-20 22:36 UTC, ystros approved these changes

2023-11-23 15:36 UTC, merged

2023-11-23 15:36 UTC, beyhan commented
Thank you @metskem!